AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: BP-ECG ETL Lambda Function

Resources:
  BpEcgEtlFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./bp_ecg_etl/
      Handler: main.lambda_handler
      Runtime: python3.12
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          SOURCE_BUCKET: "test-source-bucket"
          DEST_BUCKET: "test-dest-bucket"
          PDF_PREFIX: "pdfs/"
          BATCH_SIZE: "10"
          CONCURRENCY: "5"
